---
title: "About"
output: html_document
---

# Why cockroaches?

Asthma is one of the most common chronic illnesses for young children living in NYC according to the [NY State Department of Health](https://www.health.ny.gov/prevention/prevention_agenda/chronic_disease/). Ranging from mild to severe, asthma affects children's ability to breathe, exercise, and sleep and can severely affect children well into adulthood. 

In NYC, there are many prominent risk factors for childhood asthma including air pollution, dust mites, mice, cockroaches, and pets. Given the large presence of cockroaches in [NYC](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3271316/), children living in high-cockroach dense neighborhoods are more likely to develop asthma than children living in lower-cockroach dense neighborhoods.

Through these analyses we hope to identify and analyze risk factors for childhood asthma to map where these risk factors may have the largest impact. The current literature focuses on IgE exposure, air pollution, and the effect of impoverished neighborhoods on [childhood asthma rates](https://www.ncbi.nlm.nih.gov/pubmed/28939248) and [childhood schooling rates](https://www.cdc.gov/pcd/issues/2019/19_0074.htm). 

### Related work 

## Initial Questions 

## Data 

# Data

* We built our dataset using the [NYC Gov Environmental & Health Data Portal](http://a816-dohbesp.nyc.gov/IndicatorPublic/BuildATable.aspx). The map was built with the UHF code key from [NYC Health](http://a816-dohbesp.nyc.gov/IndicatorPublic/EPHTPDF/uhf42.pdf). The asthma CSV file we used is linked (here)[asthma_data.csv]. We selected all variables relating to asthma, cockroaches, and poverty through string detection. 

* Our github repository is linked [here](https://github.com/prisrinivasan/p8105_final)

## Exploratory analysis

## Cockroach Distribution by Borough

```{r, echo = FALSE}
library(tidyverse)
library(PerformanceAnalytics)
library(sf)
library(sp)
library(tmap)
tidy_asthma = 
  read_csv(file = "./final_data/tidy_asthma.csv")

tidy_asthma 

shape = st_read("./final_data/shapefiles/", quiet = TRUE)

tidy_asthma_sf = merge(shape, tidy_asthma, by.x = "UHFCODE", by.y = "geo_join_id") %>% 
  janitor::clean_names() %>% 
  mutate(uhfcode = as.character(uhfcode),
         time_period = as.character(time_period),
         homes_with_cockroaches = as.numeric(homes_with_cockroaches))

tidy_asthma_sf_ll = st_transform(tidy_asthma_sf, "+proj=longlat +datum=WGS84")

density_roaches = 
  tidy_asthma_sf_ll %>%
  ggplot(aes(x = homes_with_cockroaches)) + 
  geom_density() +
  facet_grid(~borough) +
  labs(
    x = "Percent of Homes with Cockroaches",
    y = "Frequency",
    title = "Distribution of Cockroaches by Borough from 2011-2014"
  ) 

density_roaches
```

## Discussion





