---
title: "lorraine"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

library(dplyr)
library(viridis)
library(sp)
library(rvest)
library(tigris)
library(maptools)
library(ggmap)
library(broom)
library(httr)
library(rgdal)
library(readxl)
library(patchwork)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

Reading in the csv file. 

```{r}
asthma_data = read.csv(file = "./final_data/asthma_data.csv") %>%
  janitor::clean_names() %>%
  mutate(
    data_value = as.numeric(data_value), 
    year = as.character(year_description)) %>%
  select(year, geo_entity_id, name, data_value) %>%
  pivot_wider(names_from = name,
              values_from = data_value) %>%
  janitor::clean_names() %>%
  view()
```

Loading and tidying the new dataset with all available data

```{r}
all_data = 
  read.csv(file = "./final_data/all_available_data.csv") %>%
  janitor::clean_names() %>%
  rename(year = time_period) %>%
  filter(data_value != "NULL",
         str_detect(name, c("[Aa]sthma", "[Cc]ockroach", "[Pp]overty")),
         !str_detect(name, c("[Nn]TA")),
         name != "Children 0-13 Years Old Ever Diagnosed with Asthma",
         name != "Youth Asthma in the Past 12 Months",
         name != "Adults Reporting Cockroaches in the Home") %>%
  mutate(
    data_value = as.numeric(data_value), 
    year = as.character(year)) %>%
  select(year, geo_join_id, name, data_value) %>%
  view()
```


