---
title: "Overview"
output: html_document

---

## Cockroach Prevalence in New York City
### Why should we care? 
* In 2017, 15.6% of households [reported](http://www.sternenvironmental.com/blog/2017/04/18/nyc-breaks-the-top-ten-list-for-worst-rat-and-cockroach-problems/) having pest infestations. One of the most common pests in NYC is cockroaches. As temperatures rise, cockroach populations are [expected](https://gothamist.com/arts-entertainment/its-summer-in-nyc-and-the-cockroaches-have-taken-flight) to increase, posing additional public health challenges, particularly among those who have asthma or respiratory reactions to cockroaches.  
* According to the [CDC](https://www.cdc.gov/pcd/issues/2019/19_0074.htm), approximately 1 in 101 schoolchildren in the United States have asthma. Of those with asthma, 49% have missed at least one day of school, costing billions of dollars in [health care use](https://www-ncbi-nlm-nih-gov.ezproxy.cul.columbia.edu/pubmed/23769497/).
* [Studies](https://www-ncbi-nlm-nih-gov.ezproxy.cul.columbia.edu/pmc/articles/PMC4803579/) showed that allergens trigger asthma attacks in 60-90% of children and in 50% of adults. Exposure to indoor environmental allergens such as cockroach, house dust mite, mice, pollen, and mold can induce allergic asthma. On average, in the United States, the prevalence of cockroach allergy ranges from 17-41% ; Cockroach allergens are detected in 85% of inner-city U.S.homes. 

### Insert Map Here 

### Asthma Hospitalization by Borough Graph

### Cockroach Prevalence by Borough Graph 

