---
title: "priyanka"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(viridis)
library(sp)
library(rvest)
library(tigris)
library(maptools)
library(ggmap)
library(broom)
library(httr)
library(rgdal)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

```{r}
pests_home = read_csv(file = "./final_data/mold_home.csv") %>%
  janitor::clean_names()

air_conc = read_csv(file = "./final_data/air_conc.csv") %>%
  janitor::clean_names()

mice_home = read_csv(file = "./final_data/mice_home.csv") %>%
  janitor::clean_names()

```

Reading JSON file for UHF geo
```{r}
uhf <- jsonlite::fromJSON("./final_data/UHF42.json", flatten = TRUE)

<<<<<<< HEAD
```
Conclusion: the JSON file is weird.

# Shape files
Shape files turned out better. Used a different file from nyc.gov because the Env & Health Data Portal file was inconsistent - combined certain neighborhoods that weren't combined in the rest of the datasets.

[Source of shape files](https://www1.nyc.gov/site/doh/data/health-tools/maps-gis-data-files-for-download.page)

```{r}
shape = st_read("./final_data/shapefiles/", quiet = TRUE)
=======
nyc_neighborhoods <- readOGR(content(uhf,'text'), 'OGRGeoJSON', verbose = F)
>>>>>>> 4b7be8f58ba56526cb65f7ef67567e47c54f230c

#look at what we have
str(shape)

<<<<<<< HEAD
#plot all polygon boundaries
plot(shape)

#plot just geometry column
plot(st_geometry(shape))
```

```{r}
merged <- merge(shape, air_conc, by.x = "UHF34_CODE", by.y = "geo_entity_id")
=======
```{r}
nyc_water = 
  GET("https://www1.nyc.gov/assets/doh/downloads/zip/uhf42_dohmh_2009.zip") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

```{r}
neigh <- GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)

>>>>>>> 4b7be8f58ba56526cb65f7ef67567e47c54f230c
```

