---
title: "Spatial"
author: "Alice Tivarovsky"
date: "11/25/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Setup and Import: 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
library(tmap)
library(sf)
library(maptools)
library(viridis)
library(leaflet)
library(RColorBrewer)

```

Load tidy_asthma: 

```{r}
tidy_asthma = 
  read_csv("./final_data/tidy_asthma.csv") 
```

## Shape files 

Reading in shape files: 

```{r}
uhf_map = 
  st_read("./final_data/shapefiles/")

str(uhf_map)
```

Joining shapefiles with tidy_asthma: 

```{r}
tidy_asthma_sf = merge(uhf_map, tidy_asthma, by.x = "UHFCODE", by.y = "geo_join_id") %>% 
  janitor::clean_names() %>% 
  mutate(uhfcode = as.character(uhfcode),
         time_period = as.character(time_period),
         homes_with_cockroaches = as.numeric(homes_with_cockroaches))

#changing geometry to latitude and longitude
tidy_asthma_sf_ll = st_transform(tidy_asthma_sf, "+proj=longlat +datum=WGS84")

#creating color palette for cockroaches
pal = colorQuantile("Reds", tidy_asthma_sf_ll$homes_with_cockroaches, n = 7)
```

## Cockroach maps - using leaflet

Cockroach prevalence by UHF in 2014: 

```{r}
tidy_asthma_sf_ll %>%
  filter(time_period == 2014) %>% 
  mutate(roach_label = str_c("Homes with Cockroaches: ", homes_with_cockroaches, "\n, Neighborhood: ", uhfcode)) %>% 
    leaflet() %>%
    addProviderTiles("CartoDB.Positron") %>%
    addPolygons(stroke = TRUE,
                weight = 2, 
                opacity = 1,
                color = ~pal(homes_with_cockroaches),
                fillOpacity = 0.8,
                smoothFactor = 0.2,
                highlight = highlightOptions(weight = 3,
                                             color = "white",
                                             bringToFront = TRUE),
                label = ~roach_label) %>% 
    addLegend("bottomright",
              pal = pal,
              values = ~homes_with_cockroaches,
              title = "% Homes with Cockroaches",
              #labFormat = labelFormat(suffix = "%"),
              opacity = 1)
```


## Asthma maps using leaflet





